# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Generate TOC in README

on:
  push:
    paths-ignore:
    - 'README.md'

    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run README generator
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/workspace \
          -e CONTENT_DIR=contents \
          -e BLOG_URL=https://blog.advenoh.pe.kr \
          kenshin579/readme-generator:latest
    - name: Create commits
      run: |
          echo "username: ${{github.actor}}"
          echo "email: ${{github.email}}"
        
          git config user.name {{github.actor}}
          git config user.email 'kenshin579@hotmail.com'
          git add README.md
          git commit -am "update README file"
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: Update README file
        branch: readme-patches
        delete-branch: true
        title: '[AUTO] Update README file'
        body: |
          Update README file
        labels: |
          automated pr
        assignees: kenshin579
        reviewers: kenshin579
